version: '3.8'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    container_name: postgres_otsc
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=OTSC
      - PGDATA=/var/lib/postgresql/data
  mongo:
    ports:
      - '27017:27017'
    container_name: mongo-files
    restart: on-failure
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongolog
      - MONGO_INITDB_ROOT_PASSWORD=mongopas
    image: mongo