version: '3.8'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres_otsc
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=OTSC
      - PGDATA=/var/lib/postgresql/data