security.jwt.token.secret-key: my-secret-key

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mongo-files
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/OTSC
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
